# A盘
fromPaths:
  - /Users/evan/project/chiaMove/tmp/A1
  - /Users/evan/project/chiaMove/tmp/A2
  - /Users/evan/project/chiaMove/tmp/A3
# B盘
toPaths:
  - /Users/evan/project/chiaMove/tmp/B1
  - /Users/evan/project/chiaMove/tmp/B2
  - /Users/evan/project/chiaMove/tmp/B3
  - /Users/evan/project/chiaMove/tmp/B4
  - /Users/evan/project/chiaMove/tmp/B5
fromPathFilter:
#  minSize: 1030792151450
#  maxSize: 1030792151451
  minSize: 1
  maxSize: 1030792151451
  prefix: 'post_'
